baseURL = "https://raidantimosquitos.github.io/network-slicing-iot/"
languageCode = "en-us"
title = "Network Slicing for IIoT"
theme = "book"

# Book configuration
disablePathToLower = true
enableGitInfo = true

[params]
    BookTitle = "Network Slicing for IIoT"
    BookTheme = "light"        # Options: auto, light, dark
    BookSearch = true          # Enable search
    BookToC = true             # Enable table of contents
    BookDateFormat = "Jan 2, 2006"
    BookRepo = "https://github.com/raidantimosquitos/network-slicing-iot/"  # Your repository link (optional)
    math = true

[markup]
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 3
        ordered = false
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        # [markup.goldmark.extensions]
        #     [markup.goldmark.extensions.passthrough]
        #         enable = true
        #         [markup.goldmark.extensions.passthrough.delimeters]
        #             block = [['\[', '\]'], ['$$', '$$']]
        #             inline = [['\(', '\)']]
    [markup.highlight]
        style = "monokai"

[menu]
    [[menu.after]]
        name = "GitHub"
        url = "https://github.com/raidantimosquitos/network-slicing-iot/"
        weight = 30

[outputs]
    home = ["HTML"]

[Languages]
    [Languages.en]
        languageName = "English"
        weight = 1

