name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment when changes are pushed to main

env:
  DEPLOY_BRANCH: gh-deployment-workflow
  HUGO_VERSION: 0.123.4 # Update this to the latest Hugo version

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        with:
          submodules: recursive # Ensure Hugo themes (if any) are fetched
          fetch-depth: 0 # Full history required for deployment

      - name: Install Hugo (Latest)
        run: |
          HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name' | sed 's/v//')
          wget https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          rm hugo_extended_${HUGO_VERSION}_linux-amd64.deb

      - name: Initialize Hugo Modules
        run: |
          cd website
          hugo mod tidy

      - name: Build the Hugo site
        run: |
          cd website
          hugo --minify -d public  # Build the site with output in 'website/public'

      - name: Checkout the deployment branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.DEPLOY_BRANCH }}
          clean: true # Ensure a clean checkout

      - name: Remove old site content
        run: |
          rm -rf ./*
          mkdir -p website

      - name: Copy new build to deployment branch
        run: |
          cp -r ../website/public/* ./website/

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy Hugo site to GitHub Pages" || echo "No changes to commit"
          git push origin ${{ env.DEPLOY_BRANCH }}
